language: go
go:
    - 1.9.x
os:
    - linux
    - osx

before_deploy:
  - GOOS=freebsd GOARCH=amd64 make
  - make release
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file_glob: true
  file: '*.{tar.gz,zip}'
  on:
    tags: true
